<a href="https://colab.research.google.com/github/BeomJinPNU/202006136/blob/main/24_05_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
data=[[1, "Alice"],[2, 'Bob'], [3, "Charlie"]]
df=pd.DataFrame(data,columns=['ID','Name'])
df

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [7]:
df.shape

(3, 2)

In [10]:
df2=pd.read_csv('data.csv')

In [12]:
df2

   name   age   score
0   Kim    27      92
1   Lee    33      98
2  Park    19      87

In [15]:
df3=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv', delimiter='\t')
df3

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,10,2,0,4,0,55,-1,90,238,157
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,11,7,4,4,1,157,55,119,154,105
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,10,2,0,2,0,113,122,53,11,157
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,11,3,0,1,0,154,39,51,90,114
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,1,0,0,1,0,11,157,141,31,18

read_excel('xlxs 파일명', sheet name=' ', index_col=0)


index col=0은 첫 번째 줄을 인덱스 명으로 활용.

데이터프레임명.info()
:데이터프레임의 칼럼들과 칼럼의 데이터 타입, 데이터 개수 등의 기본 정보를 출력한다.
non null : 값이 채워져 있다.

In [23]:
df3=pd.read_excel('data.xlsx',index_col=0)
df3

     이름 성별    국어     수학 응시여부 확인여부
반
A반  구이서  남  90.0   89.0   응시   확인
B반  김이정  여  78.0   45.0   응시   확인
A반  오지수  남   NaN    NaN   응시   확인
B반  김선후  남  33.0   44.0   응시  NaN
A반  하진희  여   0.0   85.0   응시  NaN
A반  강현진  남   NaN    NaN  NaN  NaN
B반  김진솔  남  90.0   89.0   응시   확인
B반  박서준  여  78.0   45.0   응시   확인
A반  김성희  남   NaN    NaN  NaN   확인
B반  이지서  여  86.0  100.0   응시   확인

In [31]:
df3[['이름', '성별']]

     이름 성별
반
A반  구이서  남
B반  김이정  여
A반  오지수  남
B반  김선후  남
A반  하진희  여
A반  강현진  남
B반  김진솔  남
B반  박서준  여
A반  김성희  남
B반  이지서  여

In [41]:
df3.iloc[0, 4]

'응시'

In [42]:
#국어 점수가 80점 이상인 데이터프레임
res=df3['국어'] > 80
res

반
A반     True
B반    False
A반    False
B반    False
A반    False
A반    False
B반     True
B반    False
A반    False
B반     True
Name: 국어, dtype: bool

In [47]:
# query 메서드 사용 예제
filtered_data_query = df3.query('국어 > 80')
# 출력
print(filtered_data_query)

     이름 성별    국어     수학 응시여부 확인여부
반
A반  구이서  남  90.0   89.0   응시   확인
B반  김진솔  남  90.0   89.0   응시   확인
B반  이지서  여  86.0  100.0   응시   확인

In [46]:
# 예제 데이터프레임 생성
df = pd.DataFrame({
'A': [1, 2, 3, 4, 5],
'B': [6, 7, 8, 9, 10]
})
# 'A' 열에서 값이 3보다 큰 행 선택
filtered_data = df[df['A'] > 3]
# 출력
print(filtered_data)
df

   A   B
3  4   9
4  5  10

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [49]:
#국어 점수 오름차순에 따라 나열
df3 = df3.sort_values(by=['국어'], ascending = True)
df3

     이름 성별    국어     수학 응시여부 확인여부
반
A반  구이서  남  90.0   89.0   응시   확인
B반  김진솔  남  90.0   89.0   응시   확인
B반  이지서  여  86.0  100.0   응시   확인
B반  김이정  여  78.0   45.0   응시   확인
B반  박서준  여  78.0   45.0   응시   확인
B반  김선후  남  33.0   44.0   응시  NaN
A반  하진희  여   0.0   85.0   응시  NaN
A반  오지수  남   NaN    NaN   응시   확인
A반  강현진  남   NaN    NaN  NaN  NaN
A반  김성희  남   NaN    NaN  NaN   확인

In [53]:
#결측치 확인
df3=pd.read_excel('data.xlsx',index_col=0)
df3.isna()

       이름     성별     국어     수학   응시여부   확인여부
반
A반  False  False  False  False  False  False
B반  False  False  False  False  False  False
A반  False  False   True   True  False  False
B반  False  False  False  False  False   True
A반  False  False  False  False  False   True
A반  False  False   True   True   True   True
B반  False  False  False  False  False  False
B반  False  False  False  False  False  False
A반  False  False   True   True   True  False
B반  False  False  False  False  False  False

In [60]:
#결측치에 값 채우기
df4=df3.fillna({"확인여부":"완료"})
df4

     이름 성별    국어     수학 응시여부 확인여부
반
A반  구이서  남  90.0   89.0   응시   확인
B반  김이정  여  78.0   45.0   응시   확인
A반  오지수  남   NaN    NaN   응시   확인
B반  김선후  남  33.0   44.0   응시   완료
A반  하진희  여   0.0   85.0   응시   완료
A반  강현진  남   NaN    NaN  NaN   완료
B반  김진솔  남  90.0   89.0   응시   확인
B반  박서준  여  78.0   45.0   응시   확인
A반  김성희  남   NaN    NaN  NaN   확인
B반  이지서  여  86.0  100.0   응시   확인

In [76]:
#데이터프레임 생성
df=pd.DataFrame({'학생': ['John','Alice','Bob','Emily'],
                 '수학': [90, 87, 78, 92],
                 '영어': [85, 91, 80, 88],
                 '과학': [88, 89, 85, 82]})
print(df)
#요약 통계 정보 출력
print(df.describe())
#'수학'점수가 가장 높은 학생의 정보를 출력
print(df[df['수학']==df['수학'].max()])
#'수학'점수가 90점 이상인 학생의 정보를 출력
morethan_90 = df.query('수학>=90')
print(morethan_90)

      학생  수학  영어  과학
0   John  90  85  88
1  Alice  87  91  89
2    Bob  78  80  85
3  Emily  92  88  82
              수학         영어         과학
count   4.000000   4.000000   4.000000
mean   86.750000  86.000000  86.000000
std     6.184658   4.690416   3.162278
min    78.000000  80.000000  82.000000
25%    84.750000  83.750000  84.250000
50%    88.500000  86.500000  86.500000
75%    90.500000  88.750000  88.250000
max    92.000000  91.000000  89.000000
      학생  수학  영어  과학
3  Emily  92  88  82
      학생  수학  영어  과학
0   John  90  85  88
3  Emily  92  88  82

In [98]:
#Boxoffice.xlsx 파일을 데이터프레임으로 생성하기
Boxdf = pd.read_excel('BoxOffice.xlsx')
Boxdf
#데이터프레임의 정보를 출력
Boxdf.info()
#대표국적별 영화 편수를 집계
value_counts = Boxdf['국적'].value_counts()
print(value_counts)
#대표국적이 '영국'인 데이터 출력
England = Boxdf[Boxdf['대표국적'] == '영국']
print(England)
#대표국적별 최상위 순위를 출력
highest = Boxdf.groupby('순위').min()
print(highest)

            영화명        개봉일           매출액       관객수  스크린수    상영횟수 대표국적     국적  \
순위
1            명량 2014-07-30  135758208810  17615844  1587  188724   한국     한국
2          극한직업 2019-01-23  139655543516  16266338  2003  292816   한국     한국
3     신과함께-죄와 벌 2017-12-20  115727528087  14414658  1912  214631   한국     한국
4          국제시장 2014-12-17  110945002730  14264059  1044  212698   한국     한국
5    어벤져스: 엔드게임 2019-04-24  122492181020  13977602  2835  246433   미국     미국
..          ...        ...           ...       ...   ...     ...  ...    ...
196         스파이 2013-09-05   24513098305   3436092   785   72805   한국  한국,태국
197   그것만이 내 세상 2018-01-17   27457704382   3420287   956   95444   한국     한국
198    토이 스토리 4 2019-06-20   28763352540   3400623  1336   85913   미국     미국
199           돈 2019-03-20   28870244062   3389125  1431  120809   한국     한국
200    맨 인 블랙 3 2012-05-24   27301520070   3379762   770   69538   미국     미국

                     배급사
순위
1              (주)씨제이이엔엠
2              (주)씨제이이엔엠
3          롯데쇼핑㈜롯데엔터테인먼트
4              (주)씨제이이엔엠
5     월트디즈니컴퍼니코리아 유한책임회사
..                   ...
196            (주)씨제이이엔엠
197            (주)씨제이이엔엠
198   월트디즈니컴퍼니코리아 유한책임회사
199               (주)쇼박스
200  한국소니픽쳐스릴리징브에나비스타영화㈜

[200 rows x 9 columns]